# Generated by Django 5.1.2 on 2024-11-17 14:14

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colocacion', '0001_initial'),
        ('pacientes', '0003_alter_paciente_apellido_alter_paciente_genero_and_more'),
        ('vacunas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colocacionvacuna',
            name='dosis',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='vacunas.dosis'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colocacionvacuna',
            name='fecha_aplicacion',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='colocacionvacuna',
            name='paciente',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='pacientes.paciente'),
            preserve_default=False,
        ),
    ]
