# Generated by Django 5.1.2 on 2024-10-24 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='cuil',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
